from __future__ import annotations

import os


IS_WINDOWS = os.name == "nt"
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# 환경변수 HCISUP_SDK_DIR이 있으면 우선 사용 (Docker 등 배포 환경)
# 없으면 플랫폼별 자동 선택: Windows → include/lib64, Linux → include/linux
_ENV_SDK_DIR = os.environ.get("HCISUP_SDK_DIR", "")
if _ENV_SDK_DIR and os.path.isdir(_ENV_SDK_DIR):
    DEFAULT_SDK_DIR = _ENV_SDK_DIR
elif IS_WINDOWS:
    DEFAULT_SDK_DIR = os.path.join(SCRIPT_DIR, "include", "lib64")
else:
    DEFAULT_SDK_DIR = os.path.join(SCRIPT_DIR, "include", "linux")

if IS_WINDOWS:
    DEFAULT_CMS_LIB = os.path.join(DEFAULT_SDK_DIR, "HCISUPCMS.dll")
    DEFAULT_STREAM_LIB = os.path.join(DEFAULT_SDK_DIR, "HCISUPStream.dll")
    DEFAULT_OPENSSL_CRYPTO = os.path.join(DEFAULT_SDK_DIR, "libeay32.dll")
    DEFAULT_OPENSSL_SSL = os.path.join(DEFAULT_SDK_DIR, "ssleay32.dll")
else:
    DEFAULT_CMS_LIB = os.path.join(DEFAULT_SDK_DIR, "libHCISUPCMS.so")
    DEFAULT_STREAM_LIB = os.path.join(DEFAULT_SDK_DIR, "libHCISUPStream.so")
    DEFAULT_OPENSSL_CRYPTO = os.path.join(DEFAULT_SDK_DIR, "libcrypto.so")
    DEFAULT_OPENSSL_SSL = os.path.join(DEFAULT_SDK_DIR, "libssl.so")

CFG_HCISUPCMS_PATH = DEFAULT_CMS_LIB
CFG_HCISUPSTREAM_PATH = DEFAULT_STREAM_LIB
CFG_OPENSSL_LIBCRYPTO_PATH = DEFAULT_OPENSSL_CRYPTO
CFG_OPENSSL_LIBSSL_PATH = DEFAULT_OPENSSL_SSL
CFG_LOG_DIR = "./record"
CFG_EHOME_KEY = "abc123456"
CFG_CMS_LISTEN_IP = "0.0.0.0"
CFG_CMS_PUBLIC_IP = "125.137.53.163"
CFG_CMS_LISTEN_PORT = 7660
CFG_STREAM_LISTEN_IP = "0.0.0.0"
CFG_STREAM_LISTEN_PORT = 8003
CFG_STREAM_PUBLIC_IP = "125.137.53.163"
CFG_STREAM_PUBLIC_PORT = 8003
CFG_DAS_PUBLIC_IP = "125.137.53.163"
CFG_DAS_PORT = 7660
CFG_CHANNEL = 1
CFG_STREAM_TYPE = 0
CFG_LINK_MODE = 0
CFG_RTSP_PUBLISH_URL = "rtsp://127.0.0.1:8554/isup"
CFG_QUEUE_MAX_CHUNKS = 512
CFG_SDK_DIR = DEFAULT_SDK_DIR
CFG_REGISTRATION_TIMEOUT_SEC = 0
CFG_DEBUG = True
CFG_REG_HEARTBEAT_SEC = 10
CFG_AUTO_PUBLIC_IP = "125.137.53.163"
CFG_PUSH_RETRY_COUNT = 5
CFG_PUSH_RETRY_DELAY_SEC = 1
CFG_ENABLE_PTZ_CONSOLE = True
CFG_PTZ_DEFAULT_CHANNEL = 1
CFG_PTZ_DEFAULT_SPEED = 5
CFG_PTZ_DEFAULT_DURATION_SEC = 0.3
CFG_ENABLE_CONTROL_SOCKET = True
CFG_CONTROL_SOCKET_HOST = "0.0.0.0"
CFG_CONTROL_SOCKET_PORT = 19090
CFG_VOICE_SERVER_IP = CFG_STREAM_PUBLIC_IP
CFG_VOICE_SERVER_PORT = 7500
CFG_VOICE_LISTEN_IP = "0.0.0.0"
CFG_VOICE_LISTEN_PORT = 7500
CFG_VOICE_CHANNEL = 1
CFG_VOICE_LINK_MODE = 0
CFG_VOICE_LINK_WAIT_SEC = 8
CFG_VOICE_SEND_CHUNK_BYTES = 160
CFG_VOICE_SEND_DELAY_MS = 20
